
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'data_product_demo'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'data_product_demo'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for aggregate, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - "logs"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this aggregate config, we tell dbt to build all models in the aggregate/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  +persist_docs:
    relation: true
    columns: true
  data_product_demo:
    # Config indicated by + and applies to all files under models/aggregate/
    preparation:
      +materialized: view
# enable reflections
vars:
      dremio:reflections_metadata_enabled: true

